version: '3'

services:
    webthing-server:
        image: webthing-server
        build: webthing-server
        hostname: ${COMPOSE_PROJECT_NAME}
        environment:
          RECORDING_ENABLED: 1
          RECORDING_INTERFACE: eth0
          RECORDING_PORT: 7000
          SERVER_NAME: ${COMPOSE_PROJECT_NAME}
          SERVER_PORT: 8888
          UC_INTERVAL: 60
        expose:
        - "8888"
        command: ${TEST_UC}

    webthing-client:
        image: webthing-client
        build: webthing-client
        depends_on:
        - webthing-server
        environment:
          SERVER_FRP_DOMAIN: ${COMPOSE_PROJECT_NAME}.frps
          SERVER_FRP_PORT: 8090
          UC_INTERVAL: 60
        command: ${TEST_UC}

        # command: ""
        # entrypoint: /bin/bash
        # stdin_open: true # docker run -i
        # tty: true        # docker run -t

        # volumes:
        # - "/app" # Anonymous volume
        # - "data:/data" # Named volume
        # - "mydata:/data" # External volume

networks:
  default:
    external: true
    name: frps-network

# volumes:
#     data:
#     mydata:
#         external: true